// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// validate_olc
LogicalVector validate_olc(CharacterVector codes);
RcppExport SEXP olctools_validate_olc(SEXP codesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type codes(codesSEXP);
    __result = Rcpp::wrap(validate_olc(codes));
    return __result;
END_RCPP
}
// validate_short
LogicalVector validate_short(CharacterVector codes);
RcppExport SEXP olctools_validate_short(SEXP codesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type codes(codesSEXP);
    __result = Rcpp::wrap(validate_short(codes));
    return __result;
END_RCPP
}
// validate_full
LogicalVector validate_full(CharacterVector codes);
RcppExport SEXP olctools_validate_full(SEXP codesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type codes(codesSEXP);
    __result = Rcpp::wrap(validate_full(codes));
    return __result;
END_RCPP
}
// encode_olc
CharacterVector encode_olc(NumericVector lats, NumericVector longs, IntegerVector length);
RcppExport SEXP olctools_encode_olc(SEXP latsSEXP, SEXP longsSEXP, SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type longs(longsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type length(lengthSEXP);
    __result = Rcpp::wrap(encode_olc(lats, longs, length));
    return __result;
END_RCPP
}
// decode_olc
DataFrame decode_olc(CharacterVector olcs);
RcppExport SEXP olctools_decode_olc(SEXP olcsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type olcs(olcsSEXP);
    __result = Rcpp::wrap(decode_olc(olcs));
    return __result;
END_RCPP
}
// shorten_olc
CharacterVector shorten_olc(CharacterVector olcs, NumericVector lats, NumericVector longs);
RcppExport SEXP olctools_shorten_olc(SEXP olcsSEXP, SEXP latsSEXP, SEXP longsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type olcs(olcsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type longs(longsSEXP);
    __result = Rcpp::wrap(shorten_olc(olcs, lats, longs));
    return __result;
END_RCPP
}
// recover_olc
CharacterVector recover_olc(CharacterVector olcs, NumericVector lats, NumericVector longs);
RcppExport SEXP olctools_recover_olc(SEXP olcsSEXP, SEXP latsSEXP, SEXP longsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type olcs(olcsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lats(latsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type longs(longsSEXP);
    __result = Rcpp::wrap(recover_olc(olcs, lats, longs));
    return __result;
END_RCPP
}
