# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title Check the Validity of Open Location Codes
#'@description These functions allow a useR to check whether OLCs they've
#'been provided are valid or not. \code{valid_short} identifies whether
#'a vector of OLCs are valid "short" codes; \code{valid_long} identifies
#'whether OLCs are valid "long" codes, and \code{valid_full} identifies
#'whether OLCs are valid, full stop.
#'
#'@param codes a character vector containing Open Location Codes.
#'
#'@return a vector of TRUE and FALSE values, where TRUE corresponds to a
#'valid code and FALSE an invalid.
#'
#'@examples
#'#Validate that a particular OLC is valid
#'valid_olc("WC2345+G6g")
#'#[1] TRUE
#'
#'#It is! Is it a short?
#'valid_short("WC2345+G6g")
#'#[1] TRUE
#'#Yep!
#'@export
#'@aliases olc_validate
#'@rdname olc_validate
validate_olc <- function(codes) {
    .Call('olctools_validate_olc', PACKAGE = 'olctools', codes)
}

#'@rdname olc_validate
#'@export
validate_short <- function(codes) {
    .Call('olctools_validate_short', PACKAGE = 'olctools', codes)
}

#'@rdname olc_validate
#'@export
validate_full <- function(codes) {
    .Call('olctools_validate_full', PACKAGE = 'olctools', codes)
}

#'@export
encode_olc <- function(latitude, longitude, code_length) {
    .Call('olctools_encode_olc', PACKAGE = 'olctools', latitude, longitude, code_length)
}

